name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: 🧰 Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: 📦 Grant permission to execute Gradle
        run: chmod +x ./gradlew

      - name: 🚀 Build APK
        run: ./gradlew assembleDebug

      - name: 📤 Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: VideoTVApp-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
