name: Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: 🧰 Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: 📦 Grant permission to execute Gradle
        run: chmod +x ./gradlew

      - name: 🚀 Build APK
        run: ./gradlew assembleDebug

      - name: 📤 Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          name: "VideoTVApp ${{ github.ref_name }}"
          tag_name: ${{ github.ref }}
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
